baseURL = 'https://youngyoung-0.github.io/portfolio/'
languageCode = 'ko-kr'
title = 'Portfolio'

[params]
  env = 'production'
  title = 'Portfolio'
  description = '개발 여정과 트러블슈팅을 기록하는 공간입니다.'
  author = 'Young'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

[params.profileMode]
  enabled = true
  title = "안녕하세요!👋 배움을 기록하는 개발자 Young입니다."
  subtitle = "이 공간은 제가 공부하며 배운 점과 고민들, 그리고 개발 중 겪었던 트러블슈팅 경험을 기록하기 위해 만들었습니다."
  email = "taeyoung6873@gmail.com"
  location = "Seoul, South Korea"
  github = "github.com/youngyoung-0"
  imageUrl = "assets/images/profile_image_1.JPG"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"
  buttons = [
    { name = "Blog Posts", url = "/posts/" }
  ]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40

